spring:
  datasource:
    password: ${TELEPHONE_DATASOURCE_PASSWORD}
    url: ${TELEPHONE_DATASOURCE_URL}
    username: ${TELEPHONE_DATASOURCE_USERNAME}
  liquibase:
    drop-first: true
  rabbitmq:
    password: ${TELEPHONE_RABBITMQ_PASSWORD}
    username: ${TELEPHONE_RABBITMQ_USERNAME}


fechaki:
  telephone:
    validation:
      access-key: ${TELEPHONE_NUMVERIFY_ACCESS_KEY}
      until-days: 1
    queue:
        validator:
          name: fechaki.tst.telephone.validation
        updater:
          name: fechaki.tst.telephone.updater