management:
  endpoints:
    web:
      exposure:
        include: health,info,openapi,swagger-ui

spring:
  datasource:
    password: ${TELEPHONE_DATASOURCE_PASSWORD}
    url: ${TELEPHONE_DATASOURCE_URL}
    username: ${TELEPHONE_DATASOURCE_USERNAME}
  liquibase:
    drop-first: true
  rabbitmq:
    password: ${TELEPHONE_RABBITMQ_PASSWORD}
    username: ${TELEPHONE_RABBITMQ_USERNAME}

springdoc:
  swagger-ui:
    path: /docs/index.html

fechaki:
  telephone:
    enrichment:
      access-key: ${TELEPHONE_NUMVERIFY_ACCESS_KEY}
      until-days: 1
    queue:
      enrichment:
        name: fechaki.dev.telephone.enrichment
      updater:
        name: fechaki.dev.telephone.updater